spring:
  application:
    name: sing4u
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      enabled: true
      max-file-size: 120MB
      max-request-size: 150MB
  shutdown: graceful
  config:
    import:
      - 'aws-parameterstore:/config/api/application_${spring.profiles.active}/'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  profiles:
    active: local

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

jwt:
  secret: my-jwt-secret-key-change-this-to-a-very-long-string
  access-token-validity: 900000 # 15min
  refresh-token-validity: 604800000 # 7days

cookie:
  refresh-name: refreshToken
  refresh-path: /api/v1/auth/recreate
  refresh-http-only: true
  refresh-secure: true
  refresh-same-site: None
  refresh-max-age-days: 7
  
cors:
  origin:
    - "https://www.sing4u.kr"
