spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      pool-name: HikariPool-Local
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: sing4u

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
          lob:
            non_contextual_creation: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false

  cache:
    jcache:
      config: classpath:ehcache.xml

endpoints:
  public-api-list:
    - /api/v1/health/**
    - /swagger/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /swagger-ui.html/**
    - /webjars/**
    - /api/v1/users/register
    - /v3/api-docs/**
    - /api/v1/swagger/auth
    - /api/v1/home

sing4u:
  server-url: http://localhost:8080
  file-url: https://image.sing4u.kr/

cors:
  origin:
    - "*"

springdoc:
  swagger-ui:
    enabled: true


cookie:
  refresh-name: refreshToken
  refresh-path: /api/v1/auth/recreate
  refresh-http-only: true
  refresh-secure: false
  refresh-same-site: None
  refresh-max-age-days: 7

  access-name: accessToken
  access-path: /
  access-http-only: true
  access-secure: false
  access-same-site: Lax
  access-max-age-minutes: 60



