INSERT INTO `user` (is_open, created_at, deleted_at, id, updated_at, nickname, email, password, main_cover_url, profile_image, user_public_id, account_type, role, social_type, introduction) VALUES (1, NULL, NULL, 1, NULL, 'user_1', 'test@naver.com', '{bcrypt}$2a$10$p75/S3r.7qLNUC5E.XG5cOXlhFQtW.mpEq6lmUUZu/YQMUSXN1oYy', NULL, NULL, 'user_public_id_1', 'ARTIST', 'ARTIST', 'GOOGLE', NULL);
INSERT INTO `user` (is_open, created_at, deleted_at, id, updated_at, nickname, email, password, main_cover_url, profile_image, user_public_id, account_type, role, social_type, introduction) VALUES (0, NULL, NULL, 2, NULL, 'user_2', 'test2@naver.com', '{bcrypt}$2a$10$p75/S3r.7qLNUC5E.XG5cOXlhFQtW.mpEq6lmUUZu/YQMUSXN1oYy', NULL, NULL, 'user_public_id_2', 'FAN', 'USER', 'GOOGLE', NULL);
INSERT INTO `user` (is_open, created_at, deleted_at, id, updated_at, nickname, email, password, main_cover_url, profile_image, user_public_id, account_type, role, social_type, introduction) VALUES (0, NULL, NULL, 3, NULL, 'user_3', 'test3@naver.com', '{bcrypt}$2a$10$p75/S3r.7qLNUC5E.XG5cOXlhFQtW.mpEq6lmUUZu/YQMUSXN1oYy', NULL, NULL, 'user_public_id_3', 'ARTIST', 'ARTIST', 'GOOGLE', NULL);
INSERT INTO `music_session` (artist_id, closed_at, id, started_at, status) VALUES (1, NULL, 1, NOW(), 'OPEN');
INSERT INTO `music_session` (artist_id, closed_at, id, started_at, status) VALUES (1, TIMESTAMPADD(HOUR, -1, NOW()), 2, NOW() - INTERVAL 1 HOUR, 'CLOSE');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title) VALUES (NOW(), 1, 'Spotify', 'fan1@example.com', 'track_001', 'BTS', 'Dynamite');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title) VALUES (NOW() - INTERVAL 1 DAY, 1, 'Spotify', 'fan2@example.com', 'track_002', 'BLACKPINK', 'How You Like That');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title) VALUES (NOW() - INTERVAL 2 DAY, 2, 'Spotify', 'fan3@example.com', 'track_003', 'IU', 'Blueming');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title) VALUES (NOW() - INTERVAL 3 DAY, 2, 'Spotify', 'fan4@example.com', 'track_004', '지코(ZICO)', '아무노래');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, tags) VALUES (NOW(), 1, 'Spotify', 'fan1@example.com', 'track_001', 'BTS', 'Dynamite', 'https://open.spotify.com/track/track_001', '#KPOP,#BTS,#댄스');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, tags) VALUES (NOW() - INTERVAL 1 DAY, 1, 'Spotify', 'fan2@example.com', 'track_002', 'BLACKPINK', 'How You Like That', 'https://open.spotify.com/track/track_002', '#KPOP,#GIRLGROUP,#걸그룹');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, tags) VALUES (NOW() - INTERVAL 2 DAY, 2, 'Spotify', 'fan3@example.com', 'track_003', 'IU', 'Blueming', 'https://open.spotify.com/track/track_003', '#KPOP,#발라드,#케이팝');
--INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, tags) VALUES (NOW() - INTERVAL 3 DAY, 2, 'Spotify', 'fan4@example.com', 'track_004', '지코(ZICO)', '아무노래', 'https://open.spotify.com/track/track_004', '#케이팝,#HIP,#HUMOR');
INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, like_count) VALUES (NOW(), 1, 'Spotify', 'fan1@example.com', 'track_001', 'BTS', 'Dynamite', 'https://open.spotify.com/track/track_001', 1);
INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, like_count) VALUES (NOW() - INTERVAL 1 DAY, 1, 'Spotify', 'fan2@example.com', 'track_002', 'BLACKPINK', 'How You Like That', 'https://open.spotify.com/track/track_002', 0);
INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, like_count) VALUES (NOW() - INTERVAL 2 DAY, 2, 'Spotify', 'fan3@example.com', 'track_003', 'IU', 'Blueming', 'https://open.spotify.com/track/track_003', 0);
INSERT INTO `song_request` (requested_at, session_id, music_platform_name, fan_email, platform_track_id, song_artist_name, song_title, url, like_count) VALUES (NOW() - INTERVAL 3 DAY, 2, 'Spotify', 'fan4@example.com', 'track_004', '지코(ZICO)', '아무노래', 'https://open.spotify.com/track/track_004', 0);
INSERT INTO song_request_tags (song_request_id, tag) VALUES (1, '#KPOP');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (1, '#BTS');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (1, '#댄스');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (2, '#KPOP');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (2, '#GIRLGROUP');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (2, '#걸그룹');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (3, '#KPOP');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (3, '#발라드');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (3, '#케이팝');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (4, '#케이팝');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (4, '#HIP');
INSERT INTO song_request_tags (song_request_id, tag) VALUES (4, '#HUMOR');

